version: "3"

volumes:
  db:
  redis:

services:
  daily-mysql:
    image: gcr.io/daily-ops/mysql
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:6
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6380:6379"
