apiVersion: apps/v1
kind: Deployment
metadata:
  name: besticon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: besticon
  template:
    metadata:
      labels:
        app: besticon
    spec:
      containers:
        - name: app
          image: "matthiasluedtke/iconserver:v3.9.0"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: besticon
  labels:
    app: besticon
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: besticon

